# Generated by Django 5.0.4 on 2025-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsale',
            name='frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
