# Generated by Django 5.0.4 on 2025-05-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_drugsale_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsale',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
